server:
  port: 56032

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address=true: true
    ip-address=${HOST:localhost}: ${EUREKA_HOST:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST_ZONE:http://localhost:56031/eureka/}
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, prometheus,metrics
  endpoint:
    # health:
    #   show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

spring:
  application:
    name: gateway
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: configuration-service
          uri: lb://configuration-service
          predicates:
            - Path=/config-api/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-api/**
        # Normwal Websocket route
        - id: websocket_route
          uri: ws://localhost:64613/bbn-service/websocket
          predicates:
            - Path=/bbn-api/websocket/**
        - id: websocket_route_secured
          uri: wss://localhost:64613/bbn-service/websocket
          predicates:
            - Path=/bbn-api/websocket/**
        - id: bbn-service
          uri: http://localhost:8089
          predicates:
            - Path=/bbn-api/**
        - id: lottery-service
          uri: lb://lottery-service
          predicates:
            - Path=/lottery-api/**
        - id: microtask-service
          uri: lb://microtask-service
          predicates:
            - Path=/microtask-api/**
        - id: microtask-package-service
          uri: lb://microtask-package-service
          predicates:
            - Path=/package-api/**
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscription-api/**
        - id: stories-service
          uri: lb://stories-service
          predicates:
            - Path=/stories-api/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notif-api/**
        - id: user-service
          uri: http://localhost:62592
          predicates:
            - Path=/user-api/**
        - id: payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/payment-api/**
        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/support-api/**
        - id: bbn-service
          uri: http://localhost:8089
          predicates:
            - Path=/bbn-api/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - localhost
              - http://localhost:3000
              - https://*.ngrok-free.app
              - http://localhost:4200
              - http://24.199.71.233
              - http://165.232.155.234:3000
              - http://165.232.155.234
              - http://172.20.10.6:4200
              - https://cypherfund.me
              - http://cypherfund.me
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
            allowedHeaders: "*"  
            # allowedHeaders:
            #   - Authorization
            #   - Content-Type
            allowCredentials: true
