name: Workflow for Cloud Config service

on:
  push:
    branches: [ "**" ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests

    # Optional: Upload the full dependency graph to GitHub
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    # Building Docker Image
    - name: Build Docker Image
      run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName= ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/cloud-config-service:${{ github.run_number }}${{ github.sha }}

    # Logging in to Docker Registry
    - name: Log in to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Pushing Docker Image to Registry
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/cloud-config-service:${{ github.run_number }}${{ github.sha }}
      # Replace 'registry.com/ngai-e/cloud-config-service' with your actual registry/repository name
